[package]
name = "acu-curiosity"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1", features = ["v4", "serde"], default-features = false }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
